dist: xenial
language: ruby
rvm: 2.6.3
gemfile: Gemfile
services:
  - postgresql
script: bundle exec rake test
before_install:
  - createdb pgsync_test1
  - createdb pgsync_test2
  - createdb pgsync_test3
notifications:
  email:
    on_success: never
    on_failure: change
